### ISSUE TITLE
Ability to edit the un-read server/messeges bubbles

### ISSUE THREAD

**Issue by ftk789** [TheoJustTheo/Discord-AMOLED-Theme#1]
i really like to edit the unread bubble colors, like to a color that i like, how?

**Comment by TheoJustTheo** [comment]
Unfortunately you are not able to edit the unread bubble colors with the script for this theme. Srry about that.

**Comment by ftk789** [comment]
all good man, it's all good, but it's an AMAZING theme tho, thank you for that <3
