### ISSUE TITLE
New Chrome/Discord Update made it broken 

### ISSUE THREAD

**Issue by ftk789** [TheoJustTheo/Discord-AMOLED-Theme#2]
New Chrome/Discord Update made it broken  
![image](https://user-images.githubusercontent.com/57598907/148962506-6a8517d8-5eee-49b5-a3d6-e2ac9aad35ed.png)
![image](https://user-images.githubusercontent.com/57598907/148962531-8d320036-88e3-4a98-8de2-636d580dad18.png)

**Comment by TheoJustTheo** [comment]
Thanks for notifying me. It appears that discord has changed the way the friend list looks and acts. I'll see if I could find out how to make it follow the rest of the theme. 

EDIT : (Lots of the API has changed since the last time I've touched it)

**Comment by TheoJustTheo** [comment]
I found a way to it 
(I just basically ripped the betterdiscord AMOLED theme and made it so it doesn't need the betterdiscord application)

**Comment by ftk789** [comment]
aww man so no more for the animation, the animation was cool and nice ngl, but thank you for even making this script <3
